/**
 * Deterministic security detection patterns.
 *
 * Each pattern carries a `confidence` (0–1) reflecting how reliably the regex
 * alone identifies a real vulnerability without LLM confirmation.  High-
 * confidence rules (≥ 0.85) have very specific signatures; low-confidence rules
 * (< 0.65) need the Analyst to filter noise.
 *
 * `skipInTestFiles` is true by default: findings in test/spec/fixture files are
 * suppressed for noisy rules.  Set it to false for secrets — a credential in a
 * test file is still a credential.
 *
 * IMPORTANT: this file is excluded from self-scanning (see scanner.ts
 * SKIP_REL_PATHS). Do NOT add `opensec-ignore` markers — they are not needed
 * here and create misleading documentation.
 */

import type { SecurityPattern } from './types.js'

export const SECRET_PATTERNS: SecurityPattern[] = [
  {
    name: 'AWS Access Key',
    regex: /AKIA[0-9A-Z]{16}/,
    severity: 'CRITICAL',
    confidence: 0.95,
    skipInTestFiles: false,
    category: 'secret',
    description: 'A hardcoded AWS access key ID was found in source.',
    remediation: 'Revoke the key in IAM immediately and load credentials from environment variables or a secrets manager.',
  },
  {
    name: 'AWS Secret Key',
    regex: /aws_secret_access_key\s*[=:]\s*["']?[A-Za-z0-9/+=]{40}["']?/i,
    severity: 'CRITICAL',
    confidence: 0.95,
    skipInTestFiles: false,
    category: 'secret',
    description: 'A hardcoded AWS secret access key was found.',
    remediation: 'Rotate the secret immediately and inject it via environment variables or a secrets manager.',
  },
  {
    name: 'Private Key Block',
    regex: /-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/,
    severity: 'CRITICAL',
    confidence: 0.99,
    skipInTestFiles: false,
    category: 'secret',
    description: 'A PEM-encoded private key is committed to the repository.',
    remediation: 'Remove the key from history (git filter-repo), rotate it, and store keys outside the repo.',
  },
  {
    name: 'GitHub Token',
    regex: /ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9_]{82}/,
    severity: 'CRITICAL',
    confidence: 0.98,
    skipInTestFiles: false,
    category: 'secret',
    description: 'A GitHub personal access token is hardcoded.',
    remediation: 'Revoke the token in GitHub settings and use repository or environment secrets instead.',
  },
  {
    name: 'Stripe Secret Key',
    regex: /sk_live_[a-zA-Z0-9]{24,}/,
    severity: 'CRITICAL',
    confidence: 0.99,
    skipInTestFiles: false,
    category: 'secret',
    description: 'A Stripe live secret key is hardcoded.',
    remediation: 'Revoke the key in the Stripe dashboard and load it from environment variables.',
  },
  {
    name: 'Slack Token',
    regex: /xox[baprs]-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24,}/,
    severity: 'HIGH',
    confidence: 0.97,
    skipInTestFiles: false,
    category: 'secret',
    description: 'A Slack API token is hardcoded.',
    remediation: 'Revoke the token in the Slack admin console and load it from a secret store.',
  },
  {
    name: 'Database URL with Credentials',
    regex: /(?:postgres|mysql|mongodb|redis):\/\/[^:@\s"']+:[^@\s"']+@[^\s"']+/,
    severity: 'CRITICAL',
    confidence: 0.90,
    skipInTestFiles: false,
    category: 'secret',
    description: 'A database connection string embeds inline username:password credentials.',
    remediation: 'Use a credential-less DSN and supply username/password via environment variables.',
  },
  {
    name: 'JWT Secret Hardcoded',
    regex: /jwt[_-]?secret\s*[=:]\s*["'][^"']{8,}["']/i,
    severity: 'HIGH',
    confidence: 0.75,
    skipInTestFiles: true,
    category: 'secret',
    description: 'A JWT signing secret is hardcoded as a string literal.',
    remediation: 'Store the signing secret in an environment variable; rotate any exposed secret.',
  },
  {
    name: 'Hardcoded Password Assignment',
    // Match password = "literal" but NOT password = process.env.X or password = getPassword()
    regex: /(?:password|passwd|pwd)\s*[=:]\s*["'][^"'\s]{6,}["']/i,
    severity: 'HIGH',
    confidence: 0.65,
    skipInTestFiles: true,
    category: 'secret',
    description: 'A password appears to be hardcoded as a string literal.',
    remediation: 'Move the password to an environment variable or secrets manager; never commit credentials.',
  },
  {
    name: 'Hardcoded API Key',
    regex: /api[_-]?key\s*[=:]\s*["'][^"']{10,}["']/i,
    severity: 'HIGH',
    confidence: 0.70,
    skipInTestFiles: true,
    category: 'secret',
    description: 'An API key appears to be hardcoded as a string literal.',
    remediation: 'Load the API key from configuration/environment at runtime instead of committing it.',
  },
]

export const CODE_PATTERNS: SecurityPattern[] = [
  {
    name: 'Command Injection',
    // exec/execSync with a template literal or string concatenation containing a variable
    regex: /(?:exec|execSync)\s*\(\s*[`].*\$\{|(?:exec|execSync)\s*\([^)]*\+\s*\w/,
    severity: 'CRITICAL',
    confidence: 0.75,
    skipInTestFiles: true,
    category: 'code',
    description: 'A shell command is constructed from interpolated input, allowing command injection.',
    remediation: 'Use execFile/spawn with an argument array instead of building a shell string.',
  },
  {
    name: 'SQL Injection — Template Literal',
    // Any template literal with interpolation inside a query/execute/raw call
    regex: /(?:query|execute|raw)\s*\(\s*`[^`]*\$\{[^}]+\}[^`]*`/i,
    severity: 'HIGH',
    confidence: 0.80,
    skipInTestFiles: true,
    category: 'code',
    description: 'A SQL statement is built with template literal interpolation, allowing injection.',
    remediation: 'Use parameterized queries / prepared statements instead of string interpolation.',
  },
  {
    name: 'SQL Injection — String Concat',
    regex: /(?:query|execute|raw)\s*\(\s*["'][^"']*["']\s*\+\s*\w+|["']\s*\+\s*\w+\s*\+\s*["'][^"']*(?:SELECT|INSERT|UPDATE|DELETE|WHERE)/i,
    severity: 'HIGH',
    confidence: 0.78,
    skipInTestFiles: true,
    category: 'code',
    description: 'A SQL statement is built with string concatenation, allowing injection.',
    remediation: 'Use parameterized queries / prepared statements.',
  },
  {
    name: 'eval() Usage',
    regex: /\beval\s*\([^)]{0,100}\)/,
    severity: 'HIGH',
    confidence: 0.80,
    skipInTestFiles: true,
    category: 'code',
    description: 'eval() can execute arbitrary code if its argument includes untrusted input.',
    remediation: 'Remove eval(); use JSON.parse, a safe expression parser, or explicit dispatch.',
  },
  {
    name: 'CORS Wildcard',
    regex: /Access-Control-Allow-Origin['":\s,]+\*|cors\s*\(\s*\{[^}]*origin\s*:\s*['"]?\*/,
    severity: 'HIGH',
    confidence: 0.85,
    skipInTestFiles: true,
    category: 'code',
    description: 'CORS is configured to allow any origin (*), exposing the API to any website.',
    remediation: 'Restrict Access-Control-Allow-Origin to an explicit allowlist of trusted origins.',
  },
  {
    name: 'Weak Hash Algorithm (MD5)',
    regex: /createHash\s*\(\s*['"]md5['"]\)|(?<!\w)md5\s*\(/,
    severity: 'HIGH',
    confidence: 0.85,
    skipInTestFiles: true,
    category: 'code',
    description: 'MD5 is a broken hash algorithm; collisions are trivially produced.',
    remediation: 'Use SHA-256+ for checksums, or bcrypt/argon2 for password hashing.',
  },
  {
    name: 'Weak Hash Algorithm (SHA-1)',
    regex: /createHash\s*\(\s*['"]sha1['"]\)/,
    severity: 'MEDIUM',
    confidence: 0.80,
    skipInTestFiles: true,
    category: 'code',
    description: 'SHA-1 is deprecated for security use; collision attacks exist.',
    remediation: 'Use SHA-256 or higher for any security-relevant hashing.',
  },
  {
    name: 'Insecure Random for Secret',
    // Only flag Math.random() when the result is assigned to a security-sensitive name
    regex: /(?:token|secret|nonce|csrf|session(?:Id|Token|Key)|password|key|salt)\s*[=:]\s*(?:[^;]*?)Math\.random\s*\(\)/,
    severity: 'HIGH',
    confidence: 0.85,
    skipInTestFiles: true,
    category: 'code',
    description: 'Math.random() is assigned to a security-sensitive variable and is not cryptographically secure.',
    remediation: 'Use crypto.randomBytes(32).toString("hex") for tokens, nonces, and secrets.',
  },
  {
    name: 'Open Redirect',
    regex: /res\.redirect\s*\([^)]*(?:req\.|request\.|params\.|query\.)[^)]*\)/,
    severity: 'HIGH',
    confidence: 0.82,
    skipInTestFiles: true,
    category: 'code',
    description: 'A redirect target is derived from request input, enabling open redirects.',
    remediation: 'Validate redirect targets against an allowlist of internal paths.',
  },
  {
    name: 'Path Traversal',
    regex: /(?:readFile|readFileSync|createReadStream|open)\s*\([^)]*(?:req\.|request\.|params\.|query\.)\w+[^)]*\)/,
    severity: 'HIGH',
    confidence: 0.72,
    skipInTestFiles: true,
    category: 'code',
    description: 'A file path is derived from request input, enabling path traversal attacks.',
    remediation: 'Resolve the path with path.resolve(), then verify it stays within the intended root.',
  },
  {
    name: 'Prototype Pollution',
    regex: /\[['"]__proto__['"]\]|Object\.assign\s*\(\s*\w+\s*,\s*(?:req|request|body|params)\b/,
    severity: 'HIGH',
    confidence: 0.82,
    skipInTestFiles: true,
    category: 'code',
    description: 'Merging untrusted input into objects can pollute the Object prototype.',
    remediation: 'Use Object.create(null) as merge target, or validate input keys against an allowlist.',
  },
  {
    name: 'Debug Mode Enabled',
    regex: /DEBUG\s*=\s*True|(?:app|server)\.(?:set)\s*\(\s*['"]debug['"]\s*,\s*true\s*\)/,
    severity: 'MEDIUM',
    confidence: 0.78,
    skipInTestFiles: true,
    category: 'code',
    description: 'Debug mode is explicitly enabled, which can expose stack traces and internals.',
    remediation: 'Drive debug flags from environment variables; ensure production runs with debug disabled.',
  },
  {
    name: 'HTTP Endpoint (not HTTPS)',
    // Only flag URLs that look like actual fetch targets (in string assignment or function arg)
    // Exclude: localhost, 127.x, schema namespaces, console.log strings, comments
    regex: /(?:=|fetch|axios\.get|axios\.post|got|request)\s*\(\s*['"]http:\/\/(?!localhost|127\.|0\.0\.0\.0|::1|www\.w3\.org|schemas\.)[a-zA-Z0-9]/,
    severity: 'MEDIUM',
    confidence: 0.65,
    skipInTestFiles: true,
    category: 'code',
    description: 'A plaintext http:// URL is used for a network request to a non-local host.',
    remediation: 'Use https:// for all external endpoints to prevent eavesdropping and tampering.',
  },
]

export const INFRA_PATTERNS: SecurityPattern[] = [
  {
    name: 'Docker: Running as Root',
    regex: /^USER\s+root\s*$/m,
    severity: 'HIGH',
    confidence: 0.92,
    skipInTestFiles: false,
    category: 'infra',
    description: 'The Dockerfile runs the workload as root, violating least-privilege.',
    remediation: 'Add a non-root USER directive before CMD/ENTRYPOINT.',
    files: ['Dockerfile'],
    multiline: true,
  },
  {
    name: 'Docker: Latest Tag',
    regex: /^FROM\s+\S+:latest\s*(?:#.*)?$/m,
    severity: 'MEDIUM',
    confidence: 0.92,
    skipInTestFiles: false,
    category: 'infra',
    description: 'A base image is pinned to the mutable :latest tag.',
    remediation: 'Pin base images to a specific version or digest for reproducible, auditable builds.',
    files: ['Dockerfile'],
    multiline: true,
  },
  {
    name: 'Docker: Hardcoded Secret in ENV',
    regex: /^ENV\s+(?:\w*(?:PASSWORD|SECRET|KEY|TOKEN|API_KEY)\w*)\s*=/m,
    severity: 'HIGH',
    confidence: 0.90,
    skipInTestFiles: false,
    category: 'infra',
    description: 'A secret-like environment variable is hardcoded in the Dockerfile.',
    remediation: 'Use --build-arg or Docker secrets instead of baking credentials into ENV instructions.',
    files: ['Dockerfile'],
    multiline: true,
  },
  {
    name: 'K8s: Privileged Container',
    regex: /privileged:\s*true/,
    severity: 'CRITICAL',
    confidence: 0.95,
    skipInTestFiles: false,
    category: 'infra',
    description: 'A container requests privileged mode, granting full host access.',
    remediation: 'Remove privileged:true; grant only the specific capabilities required.',
    files: ['.yaml', '.yml'],
  },
  {
    name: 'K8s: Host Network',
    regex: /hostNetwork:\s*true/,
    severity: 'HIGH',
    confidence: 0.95,
    skipInTestFiles: false,
    category: 'infra',
    description: 'The pod shares the host network namespace, bypassing network isolation.',
    remediation: 'Use a pod-level network policy instead of hostNetwork.',
    files: ['.yaml', '.yml'],
  },
  {
    name: 'K8s: Secret in Plain Env',
    regex: /name:\s*['"]?(?:\w*(?:SECRET|PASSWORD|KEY|TOKEN)\w*)['"]?\s*\n\s*value:\s*\S+/,
    severity: 'HIGH',
    confidence: 0.88,
    skipInTestFiles: false,
    category: 'infra',
    description: 'A Kubernetes env var with a secret-like name has a plaintext value.',
    remediation: 'Reference a Secret resource via secretKeyRef instead of inlining the value.',
    files: ['.yaml', '.yml'],
    multiline: true,
  },
  {
    name: 'Terraform: Public S3 Bucket',
    regex: /acl\s*=\s*["']public-read/,
    severity: 'HIGH',
    confidence: 0.92,
    skipInTestFiles: false,
    category: 'infra',
    description: 'An S3 bucket is configured for public read access.',
    remediation: 'Remove the public ACL and use bucket policies with least-privilege access.',
    files: ['.tf'],
  },
  {
    name: 'Terraform: Open Security Group',
    regex: /cidr_blocks\s*=\s*\["0\.0\.0\.0\/0"\]/,
    severity: 'HIGH',
    confidence: 0.90,
    skipInTestFiles: false,
    category: 'infra',
    description: 'A security group allows inbound traffic from any IP (0.0.0.0/0).',
    remediation: 'Restrict cidr_blocks to the specific IP ranges that need access.',
    files: ['.tf'],
  },
]

export const ALL_PATTERNS: SecurityPattern[] = [
  ...SECRET_PATTERNS,
  ...CODE_PATTERNS,
  ...INFRA_PATTERNS,
]
