/**
 * SVG renderers for README assets.
 *
 * Produces crisp, version-controllable "terminal screenshot" SVGs with no
 * headless browser required — GitHub renders these natively via <img>. The
 * runtime PNG path (screenshot.ts + puppeteer) is separate and optional.
 */

import type { DiffLine } from './screenshot.js'
import type { Finding, Severity } from './types.js'
import { tally } from './types.js'

const BG = '#0d1117'
const FG = '#c9d1d9'
const DIMC = '#8b949e'
const PINK = '#FF2D78'
const GREEN = '#00FF94'
const CHAR_W = 8.4
const LINE_H = 20
const PAD = 16

const SEV_HEX: Record<Severity, string> = {
  CRITICAL: '#ff4444',
  HIGH: '#ff8800',
  MEDIUM: '#ffd000',
  LOW: '#c9d1d9',
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

interface Span {
  text: string
  color: string
  bold?: boolean
}

function frame(lines: Span[][], cols: number): string {
  const width = Math.ceil(cols * CHAR_W) + PAD * 2
  const height = lines.length * LINE_H + PAD * 2
  const rows = lines
    .map((spans, i) => {
      const y = PAD + (i + 1) * LINE_H - 5
      let x = PAD
      const tspans = spans
        .map((s) => {
          const t = `<tspan x="${x.toFixed(1)}" y="${y}" fill="${s.color}"${s.bold ? ' font-weight="bold"' : ''}>${esc(s.text)}</tspan>`
          x += s.text.length * CHAR_W
          return t
        })
        .join('')
      return tspans
    })
    .join('\n')
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" font-family="'SF Mono','Cascadia Code',Menlo,Consolas,monospace" font-size="13">
  <rect width="${width}" height="${height}" rx="8" fill="${BG}"/>
  <text>${rows}</text>
</svg>`
}

function padCell(text: string, width: number): string {
  return text.length >= width ? text.slice(0, width) : text + ' '.repeat(width - text.length)
}

/** Render the findings table as an SVG. */
export function renderTableSvg(findings: Finding[], title = 'opensec scan ./'): string {
  const cols = [
    { label: 'SEVERITY', width: 9 },
    { label: 'RULE', width: 24 },
    { label: 'FILE', width: 24 },
    { label: 'LINE', width: 5 },
  ]
  const totalCols = cols.reduce((a, c) => a + c.width + 1, 4)
  const lines: Span[][] = []

  lines.push([{ text: '$ ', color: DIMC }, { text: title, color: GREEN, bold: true }])
  lines.push([{ text: `  ${findings.length} findings`, color: FG, bold: true }])
  lines.push([])

  const border = (l: string, m: string, r: string): Span[] => [
    { text: l + cols.map((c) => '─'.repeat(c.width + 2)).join(m) + r, color: DIMC },
  ]
  const headerText = '│' + cols.map((c) => ' ' + padCell(c.label, c.width) + ' ').join('│') + '│'
  lines.push(border('┌', '┬', '┐'))
  lines.push([{ text: headerText, color: DIMC, bold: true }])
  lines.push(border('├', '┼', '┤'))

  for (const f of findings) {
    lines.push([
      { text: '│ ', color: DIMC },
      { text: padCell(f.severity, cols[0].width), color: SEV_HEX[f.severity], bold: true },
      { text: ' │ ', color: DIMC },
      { text: padCell(f.ruleName, cols[1].width), color: FG },
      { text: ' │ ', color: DIMC },
      { text: padCell(f.file, cols[2].width), color: '#58a6ff' },
      { text: ' │ ', color: DIMC },
      { text: padCell(String(f.line), cols[3].width), color: FG },
      { text: ' │', color: DIMC },
    ])
  }
  lines.push(border('└', '┴', '┘'))

  const t = tally(findings)
  lines.push([])
  lines.push([
    { text: `  ${t.CRITICAL} CRITICAL`, color: SEV_HEX.CRITICAL, bold: true },
    { text: `  ·  ${t.HIGH} HIGH`, color: SEV_HEX.HIGH, bold: true },
    { text: `  ·  ${t.MEDIUM} MEDIUM`, color: SEV_HEX.MEDIUM },
    { text: `  ·  ${t.LOW} LOW`, color: FG },
  ])
  return frame(lines, totalCols + 2)
}

/** Render a before/after diff as an SVG. */
export function renderDiffSvg(finding: Finding, diff: DiffLine[]): string {
  const lines: Span[][] = []
  lines.push([
    { text: ` ${finding.severity} `, color: SEV_HEX[finding.severity], bold: true },
    { text: `  ${finding.ruleName}`, color: '#58a6ff', bold: true },
    { text: ` — ${finding.file}:${finding.line}`, color: DIMC },
  ])
  lines.push([{ text: finding.description, color: DIMC }])
  lines.push([])

  let maxCols = finding.description.length + 4
  for (const d of diff) {
    const prefix = d.type === 'removal' ? '- ' : d.type === 'addition' ? '+ ' : '  '
    const color = d.type === 'removal' ? '#ffa0a0' : d.type === 'addition' ? '#a0ffa0' : DIMC
    const text = prefix + d.text
    maxCols = Math.max(maxCols, text.length)
    lines.push([{ text, color }])
  }
  lines.push([])
  lines.push([{ text: '  ✓ patch generated by opensec fix', color: GREEN }])
  return frame(lines, Math.min(maxCols + 2, 100))
}

/** Render the demo "DEMO COMPLETE" banner as an SVG. */
export function renderDemoBannerSvg(count: number, seconds: number): string {
  const W = 56
  const line = (s: string): string => '║' + s + ' '.repeat(Math.max(0, W - s.length)) + '║'
  const lines: Span[][] = [
    [{ text: '╔' + '═'.repeat(W) + '╗', color: PINK }],
    [{ text: line('  🎯 DEMO COMPLETE'), color: PINK, bold: true }],
    [{ text: line(''), color: PINK }],
    [{ text: line(`  OpenSec found ${count} vulnerabilities in ${seconds}s`), color: FG }],
    [{ text: line(''), color: PINK }],
    [{ text: line('  Now scan YOUR code:  opensec scan ./'), color: GREEN }],
    [{ text: '╚' + '═'.repeat(W) + '╝', color: PINK }],
  ]
  return frame(lines, W + 2)
}
